spring:
  kafka:
    bootstrap-servers: localhost:29092
    topic: log
  datasource:
    url: jdbc:postgres://localhost:5432/news
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    change-log: liquibase/db.changelog-master.yml
  rabbitmq:
    publisher:
      logging:
        queue: news_log
        exchange: news_exchange
        routing:
          key: news.routing.key
server:
  port: 8080
